# Generated by Django 5.0.1 on 2024-01-16 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_book_category_delete_science_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
    ]
